version: '3'

services:
  frontend:
    container_name: web-server
    build: ./frontend
    restart: always
    ports:
      - 8081:80

  backend:
    container_name: api
    build: ./backend
    env_file:
      - ./.env
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:12
    env_file:
      - ./.env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data:
